# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_blogs', '0002_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
