# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_blogs', '0003_auto_20170611_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
